--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/PlayerActState.xlsx

local PlayerActStateXls = {
    IdleState = {
        Name = 'IdleState',
        Mode = 1
    },
    MoveState = {
        Name = 'MoveState',
        Mode = 1
    },
    MoveStopState = {
        Name = 'MoveStopState',
        Mode = 1
    },
    LandState = {
        Name = 'LandState',
        Mode = 1
    },
    SitBeginState = {
        Name = 'SitBeginState',
        Mode = 2
    },
    SitEndState = {
        Name = 'SitEndState',
        Mode = 2
    },
    SitState = {
        Name = 'SitState',
        Mode = 2
    },
    LieDownBeginState = {
        Name = 'LieDownBeginState',
        Mode = 3
    },
    LieDownState = {
        Name = 'LieDownState',
        Mode = 3
    },
    LieDownEndState = {
        Name = 'LieDownEndState',
        Mode = 3
    },
    JumpBeginState = {
        Name = 'JumpBeginState',
        Mode = 4
    },
    JumpHighestState = {
        Name = 'JumpHighestState',
        Mode = 4
    },
    JumpRiseState = {
        Name = 'JumpRiseState',
        Mode = 4
    },
    DoubleJumpState = {
        Name = 'DoubleJumpState',
        Mode = 4
    },
    DoubleJumpSprintState = {
        Name = 'DoubleJumpSprintState',
        Mode = 4
    },
    FallState = {
        Name = 'FallState',
        Mode = 5
    },
    CrouchBeginState = {
        Name = 'CrouchBeginState',
        Mode = 6
    },
    CrouchEndState = {
        Name = 'CrouchEndState',
        Mode = 6
    },
    CrouchIdleState = {
        Name = 'CrouchIdleState',
        Mode = 6
    },
    CrouchMoveState = {
        Name = 'CrouchMoveState',
        Mode = 6
    },
    SwimIdleState = {
        Name = 'SwimIdleState',
        Mode = 7
    },
    SwimBeginState = {
        Name = 'SwimBeginState',
        Mode = 7
    },
    SwimEndState = {
        Name = 'SwimEndState',
        Mode = 7
    },
    SwimmingEndState = {
        Name = 'SwimmingEndState',
        Mode = 7
    },
    SwimmingStartState = {
        Name = 'SwimmingStartState',
        Mode = 7
    },
    SwimmingState = {
        Name = 'SwimmingState',
        Mode = 7
    },
    FlyBeginState = {
        Name = 'FlyBeginState',
        Mode = 8
    },
    FlyEndState = {
        Name = 'FlyEndState',
        Mode = 8
    },
    FlyIdleState = {
        Name = 'FlyIdleState',
        Mode = 8
    },
    FlyMoveState = {
        Name = 'FlyMoveState',
        Mode = 8
    },
    FlySprintBeginState = {
        Name = 'FlySprintBeginState',
        Mode = 8
    },
    FlySprintEndState = {
        Name = 'FlySprintEndState',
        Mode = 8
    },
    FlySprintState = {
        Name = 'FlySprintState',
        Mode = 8
    },
    ActBeginState = {
        Name = 'ActBeginState',
        Mode = nil
    },
    ActEndState = {
        Name = 'ActEndState',
        Mode = nil
    },
    ActState = {
        Name = 'ActState',
        Mode = nil
    },
    SitOnGroundBeginState = {
        Name = 'SitOnGroundBeginState',
        Mode = 9
    },
    SitOnGroundState = {
        Name = 'SitOnGroundState',
        Mode = 9
    },
    SitOnGroundEndState = {
        Name = 'SitOnGroundEndState',
        Mode = 9
    }
}

return PlayerActStateXls
